config/routes.rb
SchoolProject::Application.routes.draw do

  namespace :admin do
    match '/', :to => 'schools#index'
    resources :schools do
      resources :students
      resources :klasses
    end
    resources :klasses do
      resources :members, :only => [:index, :create, :destroy] do
        collection do
          post :sort
        end
      end
    end
  end

  root :to => 'home#index'

end

app/models/klass.rb
class Klass < ActiveRecord::Base
  attr_accessible :name, :school_id, :student_ids

  validates_presence_of :name

  belongs_to :school
  has_many :klasses_students, :class_name => "KlassStudent", :dependent => :destroy
  has_many :students, :through => :klasses_students, :order => :position
end

app/models/klass_student.rb
class KlassStudent < ActiveRecord::Base
  set_table_name 'klasses_students'
  attr_accessible :position, :school_id, :student_id
  belongs_to :student
  belongs_to :klass
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :name

  has_many :students, :dependent => :destroy
  has_many :klasses, :dependent => :destroy

  validates_presence_of :name
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :school_id, :klass_ids

  validates_presence_of :name

  belongs_to :school
  has_many :klasses_students, :class_name => "KlassStudent", :dependent => :destroy
  has_many :klasses, :through => :klasses_students

  scope :by_name, order("name")

  def self.match(query)
    where('name like ?', "%#{query}%")
  end

  def self.except_klass_students(klass)
    ids = klass.student_ids
    ids = [0] if ids.blank?
    where("id not in (?)", ids)
  end

  def for_js
    {:id => self.id, :value => self.name}
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < InheritedResources::Base
  layout 'admin'
  USER, PASSWORD = 'admin', 'admin'
  before_filter :authenticate

  private
    
    def authenticate
      authenticate_or_request_with_http_basic do |id, password|
        id == USER && password == PASSWORD
      end
    end

end

app/controllers/admin/klasses_controller.rb
class Admin::KlassesController < Admin::DashboardController
  respond_to :html, :xml, :json
  actions :all, :except => :show

  belongs_to :school

  def create
    create! do |success, failure|
      success.html { redirect_to [:admin, parent, :klasses] }
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to [:admin, parent, :klasses] }
    end
  end   
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < Admin::DashboardController
  respond_to :html, :xml, :json, :js
  belongs_to :klass

  defaults :resource_class => Student, :collection_name => 'students', :instance_name => 'student'

  def create
    student = parent.school.students.find(params[:id])
    parent.students << student
  end

  def destroy
    student = parent.students.find(params[:id])
    parent.students.delete(student)
  end

  def sort
    student_ids = params[:students]
    klasses_students = parent.klasses_students
    klasses_students.each do |ks|
      ks.update_attribute :position, student_ids.index(ks.student_id.to_s) + 1
    end
    render :nothing => true
  end
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < Admin::DashboardController
  respond_to :html, :xml, :json
  actions :all, :except => :show 

  def create
    create! do |success, failure|
      success.html { redirect_to [:admin, :schools] }
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to [:admin, :schools] }
    end
  end   
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::DashboardController
  respond_to :html, :xml, :json
  actions :all, :except => :show 

  belongs_to :school

  def create
    create! do |success, failure|
      success.html { redirect_to [:admin, parent, :students] }
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to [:admin, parent, :students] }
    end
  end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/klasses/_form.html.slim
= simple_form_for([:admin, parent, @klass], :html => {:class => 'form-horizontal' }) do |f|
  .form-inputs 
    = f.input :name
  .form-actions 
    = f.button :submit
    | &nbsp;
    = link_to 'Cancel', [:admin, parent, :klasses], :class => 'btn btn-danger btn-mini'

app/views/admin/klasses/edit.html.slim
h1 Edit Class

hr

= render "form"

app/views/admin/klasses/index.html.slim
.pull-right
  = link_to "Add Class", [:new, :admin, parent, :klass], :class => 'btn btn-primary btn-small'
  |  
  = link_to "Students", [:admin, parent, :students], :class => 'btn btn-small'
.pull-left
  h1 #{parent.name} Classes

table.table.table-striped
  thead
    tr
      th Name
      th Students
      th
  tbody
    - @klasses.each do |klass|
      tr
        td= link_to klass.name, edit_resource_path(klass)
        td= klass.students.count
        td
          = link_to 'Assign / Sort', [:admin, klass, :members], :class => 'btn btn-success'
          |  
          = link_to 'Delete', [:admin, parent, klass], :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-mini'
    - if @klasses.blank?
      tr
        td colspan=3
          | No Classes.

app/views/admin/klasses/new.html.slim
h1 Add Class

hr

= render "form"

app/views/admin/members/_students.html.slim
h4 Students

- if parent.students.count > 0
  ol.sortable data-update=sort_admin_klass_members_path(parent, :format => :js)
    - parent.students.each do |student|
      li id="students_#{student.id}"
        i.icon-move
        |  
        = student.name
        |  
        = link_to 'delete', admin_klass_member_path(parent, student, :format => :js), :method => :delete, :remote => true

- else
  p No Students.

app/views/admin/members/create.js.erb
$('.students').html("<%= escape_javascript(render :partial => 'students') %>");
$("#q").val("");
App.fn.init_sorting();

app/views/admin/members/destroy.js.erb
$('.students').html("<%= escape_javascript(render :partial => 'students') %>");
App.fn.init_sorting();

app/views/admin/members/index.html.slim
.pull-right= link_to "Back", :back, :class => 'btn btn-primary btn-small'

.pull-left
  h1 #{parent.name} Students

.clear

p Type Student Name to add hime to the students list.

= text_field_tag :q, nil, :id => 'q', :autocomplete => "off", 'data-from' => admin_klass_members_path(parent, :format => :json), 'data-to' => admin_klass_members_path(parent, :format => :js), 'data-provide' => "typeahead", "data-items" => '6'

= content_for :on_ready do
  | App.fn.init_klass_member_association_form();
  | App.fn.init_sorting();

.students
  = render :partial => 'students'

app/views/admin/members/index.json.erb
<%= parent.school.students.match(params[:query]).except_klass_students(parent).collect(&:for_js).to_json.html_safe %>

app/views/admin/schools/_form.html.slim
= simple_form_for([:admin, @school], :html => {:class => 'form-horizontal' }) do |f|
  .form-inputs 
    = f.input :name
  .form-actions 
    = f.button :submit
    | &nbsp;
    = link_to 'Cancel', [:admin, :schools], :class => 'btn btn-danger btn-mini'

app/views/admin/schools/edit.html.slim
h1 Edit School

hr

= render "form"

app/views/admin/schools/index.html.slim
.pull-right= link_to "Add School", [:new, :admin, :school], :class => 'btn btn-primary btn-small'
.pull-left
  h1 Schools

table.table.table-striped
  thead
    tr
      th Name
      th Students
      th Classes
      th
  tbody
    - @schools.each do |school|
      tr
        td= link_to school.name, edit_resource_path(school)
        td= school.students.count
        td= school.klasses.count
        td
          = link_to 'Classes', [:admin, school, :klasses], :class => 'btn btn-mini'
          |  
          = link_to 'Students', [:admin, school, :students], :class => 'btn btn-mini'
          |  
          = link_to 'Delete', [:admin, school], :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-mini'
    - if @schools.blank?
      tr
        td colspan=4
          | No Schools.

app/views/admin/schools/new.html.slim
h1 Add School

hr

= render "form"

app/views/admin/students/_form.html.slim
= simple_form_for([:admin, parent, @student], :html => {:class => 'form-horizontal' }) do |f|
  .form-inputs 
    = f.input :name
    = f.association :klasses, :as => :check_boxes, :label => "Classes", :collection => parent.klasses
  .form-actions 
    = f.button :submit
    | &nbsp;
    = link_to 'Cancel', [:admin, parent, :students], :class => 'btn btn-danger btn-mini'

app/views/admin/students/edit.html.slim
h1 Edit Student

hr

= render "form"

app/views/admin/students/index.html.slim
.pull-right
  = link_to "Add Student", [:new, :admin, parent, :student], :class => 'btn btn-primary btn-small'
  |  
  = link_to "Classes", [:admin, parent, :klasses], :class => 'btn btn-small'
.pull-left
  h1 #{parent.name} Students

table.table.table-striped
  thead
    tr
      th Name
      th
  tbody
    - @students.each do |student|
      tr
        td= link_to student.name, edit_resource_path(student)
        td= link_to 'Delete', [:admin, parent, student], :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-mini'
    - if @students.blank?
      tr
        td colspan=2
          | No Students.

app/views/admin/students/new.html.slim
h1 Add Student

hr

= render "form"

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/_application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Delta School"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    link href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144"
    link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"
    link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"
    link href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed"
    link href="/favicon.ico" rel="shortcut icon"

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/" Delta - School
          .container-fluid.nav-collapse
            - if content_for?(:top_navigation)
              = yield :top_navigation
              ul.nav.pull-right
                li= link_to 'Exit', root_path
            - else
              ul.nav.pull-right
                li= link_to "Manage", "/admin"

    .container-fluid
      .span12
        = yield
    
        footer
          p &copy; Delta - School 2012
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    javascript:
      $(function() { 
       #{yield :on_ready}
      });

app/views/layouts/admin.html.slim
= content_for :top_navigation do
  ul.nav.pull-left
    li= link_to "Schools", [:admin, :schools]

= render :layout => 'layouts/application' do
  = yield

app/views/layouts/application.html.slim
= render :partial => 'layouts/application'